// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.DataContextClass;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductsApi.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCategory")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = "1",
                            CreatedBy = "Seeder",
                            CreatedDate = new DateTime(2025, 6, 20, 18, 58, 13, 383, DateTimeKind.Utc).AddTicks(3694),
                            ImageUrl = "https://example.com/images/mouse.jpg",
                            ProductCategory = "Electronics",
                            ProductDescription = "Ergonomic wireless mouse with 2.4GHz connection",
                            ProductName = "Wireless Mouse",
                            ProductPrice = 29.99m
                        },
                        new
                        {
                            ProductId = "2",
                            CreatedBy = "Seeder",
                            CreatedDate = new DateTime(2025, 6, 20, 18, 58, 13, 383, DateTimeKind.Utc).AddTicks(3698),
                            ImageUrl = "https://example.com/images/speaker.jpg",
                            ProductCategory = "Audio",
                            ProductDescription = "Portable Bluetooth speaker with HD sound",
                            ProductName = "Bluetooth Speaker",
                            ProductPrice = 49.99m
                        },
                        new
                        {
                            ProductId = "3",
                            CreatedBy = "Seeder",
                            CreatedDate = new DateTime(2025, 6, 20, 18, 58, 13, 383, DateTimeKind.Utc).AddTicks(3701),
                            ImageUrl = "https://example.com/images/watch.jpg",
                            ProductCategory = "Wearables",
                            ProductDescription = "Fitness tracking smart watch with heart rate monitor",
                            ProductName = "Smart Watch",
                            ProductPrice = 99.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
