// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderApi.DbContextClass;

#nullable disable

namespace OrderApi.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20250620185729_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderApi.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("OrderDetailsId")
                        .IsUnique()
                        .HasDatabaseName("IDX_OrderDetailsId)");

                    b.ToTable("OrderDetails", (string)null);

                    b.HasData(
                        new
                        {
                            OrderDetailsId = 1,
                            Count = 5,
                            CreatedDate = new DateTime(2025, 6, 20, 18, 57, 25, 332, DateTimeKind.Utc).AddTicks(2434),
                            Price = 29.99m,
                            ProductId = "1",
                            ProductName = "Wireless Mouse"
                        },
                        new
                        {
                            OrderDetailsId = 2,
                            Count = 5,
                            CreatedDate = new DateTime(2025, 6, 20, 18, 57, 25, 332, DateTimeKind.Utc).AddTicks(2436),
                            Price = 49.99m,
                            ProductId = "2",
                            ProductName = "Bluetooth Speaker"
                        },
                        new
                        {
                            OrderDetailsId = 3,
                            Count = 5,
                            CreatedDate = new DateTime(2025, 6, 20, 18, 57, 25, 332, DateTimeKind.Utc).AddTicks(2437),
                            Price = 99.99m,
                            ProductId = "3",
                            ProductName = "Smart Watch"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
